version: "3.2"

services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    ports: 
      - ${RMQ_PORT}:15672
    volumes:
      - dbdata:/data/rabbitmq

  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports: 
      - ${DB_PORT}:27017
    environment: 
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - dbdata:/data/db
  
  api:
    image: node:14.16.1-alpine3.13
    container_name: api
    restart: always
    env_file: 
      - .env
    depends_on: 
      - db
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    logging:
      driver: "json-file"
      options: 
        max-size: "10m" 
        max-file: "5" 

volumes:
  dbdata: